### ISSUE TITLE
Trouble loading plans

### ISSUE THREAD

**Issue by lks-mn** [ideacrew/hra_calculator#43]
I have tried loading plans in the HRA Admin Portal.  We have the xml and xlsx files for each carrier in correct folder structure with the naming conventions noted on the Community site. However, I keep getting error "Plan XML does not exist for carrier: Medica" .  I even changed the "p" to "P" in Plan.xml thinking the capital P in the error message could be a clue.  Now I get a similar error but it is for HealthPartners plans. (Folder structure example for Medica: serff_templates.zip/serff templates/Medica/Plan.xml ; rates.xml ; service_areas.xlsx.)

**Comment by DFos85** [comment]
Good evening @lks-mn what version of the tool are are you using? Release 0.1.0, 0.2.0 or 0.3.0?

**Comment by DFos85** [comment]
@lks-mn any progress made on the issue noted? Happy to help where I can.

**Comment by lks-mn** [comment]
Thanks for checking. No progress.

I think the version we have 0.3.0. -- our current install was October 22.

**Comment by DFos85** [comment]
Ok. Plan loading instructions are valid for release 0.3.0. So lets dig into where the issue is occuring. Is the loading stopping a certain point. Meaning are any plans successfully loading?

**Comment by lks-mn** [comment]
Thanks for your reply and sorry for my delayed response.

We have decided to postpone using this application.
